### PR TITLE
Implemented multiplayer functionality and game logic

### PR DESCRIPTION
**Pull request by MichaelNey**

### CODE REVIEW

**Comment by MichaelNey** [comment]
#26 Simple multiplayer implementation. We have no game logic. This consists of an online player count, submitting guess to server, and setting username.

**Comment by MichaelNey** [comment]
Implemented complete multiplayer functionality, along with back-end game logic.

Features:

- Set username
- Guess letter
- Game over on 6 failed guesses
- Can't repeat guess the same letter
- Online Players count
- New game starts 5 seconds after victory or loss, and updates client side
- Multiplayer functionality, everyone plays the same game.

**Comment by KenavR** [comment]
## Getting it running

I am not sure, but I believe you copied the `socket.js` manually to the `dist` directory since the build system doesn't do that the socket connection didn't work (`io` was not available). 

There are a couple of ways to fix that and I need your feedback to tell me if I should change the build system. Currently, everything that is imported/required web pack adds to the bundle.js. Other than in the past the build process does not add loaded libraries to the `window` object. Which means rather than just using the `io` object you need to import/require it, like in node. I made the following changes to get it running without changing the build process.

### clientSocket.js
Added the following line to the top of the file

```js
    var io = require("socket.io-client");
```

### index.html
Removed `<script src="socket.js"></script>`

### socket.js
Deleted the file, because `socket.io-client` get imported from the node_modules.

Let me know if you'd rather use it differently.

-----------------------------------------------------------------

## Regarding the new code
I generally like the structure, it has a clear distinction between `Actions` and `Callbacks`. The only two improvements I would make are

1. Cache dom nodes
`document.getElementById('game-message')` is called every time a message comes in. Rather than querying the dom in every callback, you could query it once at the beginning, store it in a variable and use that. => less DOM interaction = better performance (not really important here but for the future)

1. Make it DRY-er (Don't repeat yourself)
The socket callbacks all look very similar, you could create a single function and reuse it for every message.

**Comment by KenavR** [comment]
@TheGrimJam Was I the only one having the starting issue? Did you merge even though it breaks the project?

**Pull request merged**
